### ISSUE TITLE
`image:` syntax on non-bots repo doesn't do what it should

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/bots#4951]
With our split scenarios on `cockpit` repo, it's potentially interesting to trigger all scenarios of a given image.  I thought that maybe `image:fedora-testing` would do that, but it got me this, instead:

```
⬢[lis@toolbox main]$ bots/tests-trigger 19046 image:fedora-testing
fedora-testing@cockpit-project/cockpit-podman: triggering on pull request 19046
fedora-testing/daily@cockpit-project/cockpit: triggering on pull request 19046
fedora-testing@cockpit-project/cockpit: triggering on pull request 19046
fedora-testing@cockpit-project/cockpit-machines: triggering on pull request 19046
```

which makes no sense at all.  I'd rather expect that this is the equivalent of

```
⬢[lis@toolbox main]$ bots/tests-trigger 19046 fedora-testing/{expensive,networking,other,storage}
fedora-testing/expensive: triggering on pull request 19046
fedora-testing/storage: triggering on pull request 19046
fedora-testing/other: triggering on pull request 19046
fedora-testing/networking: triggering on pull request 19046
```

While we're at it, though, we might also imagine `tests-trigger scenario:storage` to run the given sub-scenario against all images.

**Comment by martinpitt** [comment]
Actually no, it's working exactly as it should. The testmap does *not* split the fedora-testing image into scenarios, mostly because these are much less time critical (no human is waiting for this). If you try e.g. `./tests-trigger -n 4885 image:fedora-38` you get the full scenario explosion.

So the way to "fix" this would be to split the fedora-testing scenario in the test map, if we care.
