### ISSUE TITLE
Image refresh for openshift

### ISSUE THREAD

**Issue by cockpituous** [cockpit-project/bots#585]
Image refresh for openshift
 * [ ] FAIL: image-refresh openshift

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-04.
Log: https://logs.cockpit-project.org/logs/image-refresh-585-20200228-110303/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-585-20200228-110303/

**Comment by cockpituous** [comment]
image-refresh in progress on 3-ci-srv-03.
Log: https://logs.cockpit-project.org/logs/image-refresh-585-20200302-202727/

**Comment by cockpituous** [comment]
Task failed: https://logs.cockpit-project.org/logs/image-refresh-585-20200302-202727/

**Comment by marusak** [comment]
```
Step 1/4 : ARG VERSION=latest
Please provide a source image with `from` prior to commit
image-create: setup failed with code 1
```
:)

**Comment by martinpitt** [comment]
This is because building the cockpit/base container here needs a VERSION hack similar to the docker variant in fedora.setup. However, this is only necessary for the container-kubernetes test on rhel-7.8. We don't currently run this, but I think we should. I'll look into reviving this and fixing the base container.
